#!/usr/bin/env bash
set -euo pipefail

fail() { echo "Renderer test: $*" >&2; exit 1; }
[[ $EUID -ne 0 ]] || fail 'Run as your desktop user, never root.'
argo_root=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)
renderer_workspace=${FLUTTER_WORKSPACE:-"$HOME/dev/infotainment"}
renderer_ihs=${IHS_PREFIX:-"$HOME/dev/ivi-build/out/usr/local"}
[[ -d "$renderer_workspace" ]] || fail "Missing workspace: $renderer_workspace"
renderer_workspace=$(cd -- "$renderer_workspace" && pwd)
if [[ -f "$renderer_workspace/setup_env.sh" ]]; then
  # Generated by the installed emb CLI; supplies Flutter, Dart and pub cache.
  source "$renderer_workspace/setup_env.sh"
fi
# Dart's installed CLI location on the VM (also allow an existing PATH entry).
if ! command -v emb >/dev/null && [[ -x "$HOME/.local/state/Dart/install/bin/emb" ]]; then
  export PATH="$HOME/.local/state/Dart/install/bin:$PATH"
fi
export FLUTTER_WORKSPACE="$renderer_workspace"
export IHS_PREFIX="$renderer_ihs"
renderer_bundle="$renderer_workspace/bundle/argo-render-test"
renderer_build="$argo_root/build/native-projection-render-test"
renderer_executable="$IHS_PREFIX/bin/homescreen"
for command in cmake ninja pkg-config gst-inspect-1.0 emb flock pgrep; do
  command -v "$command" >/dev/null || fail "Required command missing: $command (load your emb CLI environment)."
done
[[ -x "$renderer_executable" ]] || fail "Missing executable: $renderer_executable"
[[ -f "$IHS_PREFIX/include/ihs/platform_view.h" ]] || fail 'Missing IHS platform-view header.'
[[ -f "$IHS_PREFIX/lib/libihs_shared.so" ]] || fail 'Missing IHS lib/libihs_shared.so.'
gst-inspect-1.0 videotestsrc >/dev/null || fail 'Install the GStreamer videotestsrc plugin.'
# Hold the lock through building, staging and execution. Also catch homescreen
# instances launched manually, before any potentially in-use library is replaced.
exec 9>"/tmp/argo-renderer-test-$UID.lock"
flock -n 9 || fail 'Stop the previous renderer-test launcher first.'
if pgrep -u "$UID" -x homescreen >/dev/null; then
  fail 'Stop the previous homescreen process before rebuilding/staging the native library.'
fi
# A workspace cross-compilation environment must not redirect system GStreamer.
unset PKG_CONFIG_SYSROOT_DIR PKG_CONFIG_LIBDIR
cmake -S "$argo_root/native/projection/argo-projection-view" \
  -B "$renderer_build" -G Ninja -DCMAKE_BUILD_TYPE=Release \
  -DIHS_INCLUDE_DIR="$IHS_PREFIX/include" \
  -DIHS_SHARED_LIBRARY="$IHS_PREFIX/lib/libihs_shared.so"
cmake --build "$renderer_build"
cd -- "$renderer_workspace"
emb bundle --app-path "$argo_root" --workspace "$renderer_workspace" \
  --arch x86_64 --mode release --build --output "$renderer_bundle"
install -m 755 "$renderer_build/libargo_projection_view.so" \
  "$renderer_bundle/lib/libargo_projection_view.so"
for library in libapp.so libflutter_engine.so libargo_projection_view.so libveloce_lua_native.so libsqlite3.so; do
  [[ -f "$renderer_bundle/lib/$library" ]] || fail "Missing bundled library: $library"
done
# Clear inherited Argo/Veloce integrations, scenarios, sockets and credentials.
# Preserve explicit DRM selection and opt-in geometry logging; otherwise native discovery wins.
for variable in ${!ARGO_@} ${!VELOCE_@}; do
  [[ "$variable" == ARGO_PROJECTION_DRM_RENDER_NODE || "$variable" == ARGO_PROJECTION_GEOMETRY_DIAGNOSTICS ]] || unset "$variable"
done
renderer_state=$(mktemp -d /tmp/argo-renderer-test.XXXXXX)
trap 'rm -rf -- "$renderer_state"' EXIT
mkdir "$renderer_state/plugins" "$renderer_state/integrations" "$renderer_state/storage"
export ARGO_PROJECTION_RENDER_TEST=1 ARGO_PROJECTION_BACKEND=disabled
export ARGO_MODE=simulation ARGO_HOST_POWER_BACKEND=disabled ARGO_AUDIO_BACKEND=disabled
export ARGO_VEHICLE_PROFILE=generic
export ARGO_VEHICLE_INTEGRATIONS_DIR="$renderer_state/integrations"
export ARGO_SETTINGS_FILE="$renderer_state/settings.json"
export VELOCE_PLUGIN_DIR="$renderer_state/plugins" VELOCE_PLUGIN_STORAGE="$renderer_state/storage"
export VELOCE_LUA_LIBRARY="$renderer_bundle/lib/libveloce_lua_native.so"
export LD_LIBRARY_PATH="$IHS_PREFIX/lib:$renderer_bundle/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
# pipefail preserves homescreen failure even when tee succeeds.
"$renderer_executable" -b "$renderer_bundle" --backend wayland-egl --w=1280 --h=720 \
  2>&1 | tee /tmp/argo-renderer-test.log
